export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_GET_FORMS_SUCCESS = "USER_GET_FORMS_SUCCESS";
export const USER_GET_FORMS_FAIL = "USER_GET_FORMS_FAIL";

export const USER_GET_FORM_SUCCESS = "USER_GET_FORM_SUCCESS";
export const USER_GET_FORM_FAIL = "USER_GET_FORM_FAIL";